"""empty message

Revision ID: be5af805c5d0
Revises: c76409ac94da
Create Date: 2023-09-30 17:06:33.813622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be5af805c5d0'
down_revision: Union[str, None] = 'c76409ac94da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('email', sa.String(), nullable=True))
    op.drop_constraint('tokens_chat_id_key', 'tokens', type_='unique')
    op.create_unique_constraint(None, 'tokens', ['email'])
    op.drop_column('tokens', 'chat_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tokens', type_='unique')
    op.create_unique_constraint('tokens_chat_id_key', 'tokens', ['chat_id'])
    op.drop_column('tokens', 'email')
    # ### end Alembic commands ###
